development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://pffkangifcmdnl:4b99610ad57c44bfd16bb929dd2793de5fdb03301b833637544a2b2de9b910b5@ec2-50-19-83-146.compute-1.amazonaws.com:5432/d15aj191svusnp
